version: '3.9'
services:
  db:
    image: mysql:8.4.0
    restart: no
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_COLLATION: utf8mb4
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    restart: no
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 8080:80
    networks:
      - app-network
  cache:
    image: redis:7.2.4-alpine
    restart: no
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache:/data
networks:
  app-network:
    driver: bridge
volumes:
  db_data:
  cache:
    driver: local
